Removing ElasticSearch Brew instructions (#10370)
* Removing ElasticSearch Brew instructions

If you try to install brew as directed you get this Error:
Error: Calling Installation of elasticsearch-oss from a GitHub commit URL is disabled! Use 'brew extract elasticsearch-oss' to stable tap on GitHub instead.

Brew/ElasticSearch no longer allows you to tap as we previously have suggested in the doc. Also we can no longer grab the 7.5.2 version with brew. 

We have decided to remove the instructions for now until we upgrade ElasticSearch if possible.

* Adding recommended changes. 

Added back line 15 per Nicks recommendation  (i.e. with rbenv: `rbenv install $(cat .ruby-version)`)

Line 65  updated to  7.5 or higher for Elasticsearch per Rhymes recommendation
~Forem requires a version of Elasticsearch 7.5 or higher to be running.  We recommend version 7.5.2.~

Line 110 update:
Added back in the Homebrew instructions but updated commands to `install elastic/tap/elasticsearch-oss`

* Updating wording per Molly's suggestion

Updating "to be running " to "run" and adjusting line 64 to "Forem requires Elasticsearch 7.x to run. We recommend version 7.5.2."